name: '"iamlive" Action For GitHub Actions'
description: 'Capture the used AWS IAM permissions using client-side monitoring (CSM) from your GitHub actions workflow.'
branding:
  icon: 'cloud'
  color: 'orange'
author: Marco Franssen
inputs:
  iamlive-version:
    description: >-
      The iamlive version you want to use (defaults to v1.1.8).
    required: false
    default: v1.1.8
  auto-capture:
    description: >-
      If enabled, iamlive will auto-capture the policy in the given output-file and upload it as artifact.
    required: false
    default: "false"
  output-file:
    description: >-
      The file to write the policy to (defaults to iamlive-policy.json).
    required: false
    default: iamlive-policy.json
outputs:
  iamlive-version:
    description: 'The iamlive version that was installed'
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/capture-policy/index.js'
